apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    grafana_datasource: "1"
    app.kubernetes.io/name: {{ .Chart.Name }}
data:
  datasources.yaml: |
    apiVersion: 1
    {{- if .Values.datasources }}
    datasources:
{{ toYaml .Values.datasources | indent 4 }}
    {{- else }}
    datasources:
    - name: Prometheus
      type: prometheus
      uid: prometheus
      url: http://kube-prometheus.{{ .Values.prometheusNamespace | default "app-prometheus" }}.svc.cluster.local:9090
      access: proxy
      isDefault: true
{{- end }}
