domain: "example.com"
project: "my-gcp-project"
registry: "gcr.io/my-gcp-project"
robots: []

# The default requests/limits are sufficient for small deployments with a few
# robots. For a large deployment with ~30 robots, you might need ~2CPU and
# ~12Gi mem.
# TODO(rodrigoq): can we reduce this by updating prometheus?
limits:
  cpu: "2000m"
  memory: "2Gi"

# The default persistent disk size. You need to adjust this defeping your fleet
# size and desired retention time.
#
# To compute the disk space required we used the formula in
# https://devops.stackexchange.com/questions/9298/how-to-calculate-disk-space-required-by-prometheus-v2-2
#
# retention_time_seconds = 90 * 24 * 60 * 60
# ingested_samples_per_second = avg(sum(rate(prometheus_tsdb_head_samples_appended_total[1d]))) = ~7000
# bytes_per_sample = avg(sum(rate(prometheus_tsdb_compaction_chunk_size_bytes_sum[1d]) /
#                            rate(prometheus_tsdb_compaction_chunk_samples_sum[1d]))) = ~1.0
# needed_disk_space = retention_time_seconds * ingested_samples_per_second * bytes_per_sample = ~72G
# Use a larger volume to account for future growth.
requests:
  storage: "200Gi"
retention:
  time: "90d"
  # Keep in sync with the disksize above and keep some headroom to avoid alerts.
  size: "180GB"

# Grafana HTTP configuration
gf_server_domain: "${CLOUD_ROBOTICS_DOMAIN}"
gf_server_root_url: "https://${CLOUD_ROBOTICS_DOMAIN}/grafana"
# Grafana Ingress configuration. Does not use the same replace as the values above.
gf_ingress_auth_url: "http://oauth2-proxy.default.svc.cluster.local/apis/core.token-vendor/v1/token.verify"
gf_ingress_auth_signin: "https://{{ .Values.domain }}/oauth2/start?rd=$escaped_request_uri"
gf_ingress_error_page_403: "https://{{ .Values.domain }}/oauth2/start?rd=$escaped_request_uri"
# Prometheus
prom_ingress_auth_url: "http://oauth2-proxy.default.svc.cluster.local/apis/core.token-vendor/v1/token.verify"
prom_ingress_auth_signin: "https://{{ .Values.domain }}/oauth2/start?rd=$escaped_request_uri"
prom_ingress_error_page_403: "https://{{ .Values.domain }}/oauth2/start?rd=$escaped_request_uri"
