// Copyright 2026 The Cloud Robotics Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	appsv1alpha1 "github.com/googlecloudrobotics/core/src/go/pkg/apis/apps/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ChartAssignmentLister helps list ChartAssignments.
// All objects returned here must be treated as read-only.
type ChartAssignmentLister interface {
	// List lists all ChartAssignments in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*appsv1alpha1.ChartAssignment, err error)
	// Get retrieves the ChartAssignment from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*appsv1alpha1.ChartAssignment, error)
	ChartAssignmentListerExpansion
}

// chartAssignmentLister implements the ChartAssignmentLister interface.
type chartAssignmentLister struct {
	listers.ResourceIndexer[*appsv1alpha1.ChartAssignment]
}

// NewChartAssignmentLister returns a new ChartAssignmentLister.
func NewChartAssignmentLister(indexer cache.Indexer) ChartAssignmentLister {
	return &chartAssignmentLister{listers.New[*appsv1alpha1.ChartAssignment](indexer, appsv1alpha1.Resource("chartassignment"))}
}
