// Copyright 2026 The Cloud Robotics Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	appsv1alpha1 "github.com/googlecloudrobotics/core/src/go/pkg/apis/apps/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ResourceSetLister helps list ResourceSets.
// All objects returned here must be treated as read-only.
type ResourceSetLister interface {
	// List lists all ResourceSets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*appsv1alpha1.ResourceSet, err error)
	// Get retrieves the ResourceSet from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*appsv1alpha1.ResourceSet, error)
	ResourceSetListerExpansion
}

// resourceSetLister implements the ResourceSetLister interface.
type resourceSetLister struct {
	listers.ResourceIndexer[*appsv1alpha1.ResourceSet]
}

// NewResourceSetLister returns a new ResourceSetLister.
func NewResourceSetLister(indexer cache.Indexer) ResourceSetLister {
	return &resourceSetLister{listers.New[*appsv1alpha1.ResourceSet](indexer, appsv1alpha1.Resource("resourceset"))}
}
