// Copyright 2019 The Cloud Robotics Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/googlecloudrobotics/core/src/go/pkg/apis/apps/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ResourceSetLister helps list ResourceSets.
type ResourceSetLister interface {
	// List lists all ResourceSets in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.ResourceSet, err error)
	// Get retrieves the ResourceSet from the index for a given name.
	Get(name string) (*v1alpha1.ResourceSet, error)
	ResourceSetListerExpansion
}

// resourceSetLister implements the ResourceSetLister interface.
type resourceSetLister struct {
	indexer cache.Indexer
}

// NewResourceSetLister returns a new ResourceSetLister.
func NewResourceSetLister(indexer cache.Indexer) ResourceSetLister {
	return &resourceSetLister{indexer: indexer}
}

// List lists all ResourceSets in the indexer.
func (s *resourceSetLister) List(selector labels.Selector) (ret []*v1alpha1.ResourceSet, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ResourceSet))
	})
	return ret, err
}

// Get retrieves the ResourceSet from the index for a given name.
func (s *resourceSetLister) Get(name string) (*v1alpha1.ResourceSet, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("resourceset"), name)
	}
	return obj.(*v1alpha1.ResourceSet), nil
}
