# Image used for integration_test.sh on Cloud Build.
# Allows access to GKE and to run Bazel commands.
FROM gcr.io/cloud-builders/kubectl

# https://bazel.build/install/ubuntu#install-on-ubuntu
RUN \
    apt-get update && \
    apt-get install apt-transport-https curl gnupg -y && \
    curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg && \
    mv bazel-archive-keyring.gpg /usr/share/keyrings && \
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list && \

    apt-get update && \
    apt-get install -y \
      bazel-6.2.0 \
      git \
      jq && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \

    ln -s /usr/bin/bazel-6.2.0 /usr/bin/bazel && \
    # Unpack Bazel for future use.
    bazel version

# rules_python is not happy if bazel runs as root so create a new user
# https://github.com/bazelbuild/rules_python/pull/713
# https://github.com/GoogleCloudPlatform/cloud-builders/issues/641
RUN mkdir -p /builder /output /workspace && chmod -R 777 /output
RUN adduser builder
USER builder
