# A Cloud Build job for running integration_test.sh.
# TODO(b/323509860): Run directly on the Action runner when it supports WIF.
steps:
  # Needed for cloud build to allow running Bazel as non-root, see
  # https://github.com/GoogleCloudPlatform/cloud-builders/issues/641#issuecomment-604599102
  # Not part of the Dockerfile since the chmod layer adds significant image size.
  - name: ubuntu
    entrypoint: "bash"
    args: ["-c", "chmod -R 777 /builder && chmod -R 777 /workspace"]

  # This runs on a custom image that has kubectl, gcloud and bazel installed.
  # See Dockerfile.integration-test-image.
  - name: "gcr.io/robco-integration-test/integration-test-image@sha256:2d5a14c82e1ce86a280678031ecf79536ccad6ced272926f78161dc4da16ba4a"
    entrypoint: "bash"
    args: ["./.github/ci/integration_test.sh"]
    env:
      - "GITHUB_SHA=${_GITHUB_SHA}"
      - "MANUAL_RUN=${_MANUAL_RUN}"

substitutions:
  _GITHUB_SHA: ""
  _MANUAL_RUN: ""

options:
  dynamicSubstitutions: true
  substitutionOption: "MUST_MATCH"
timeout: 1200s
