// Copyright 2026 The Cloud Robotics Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/googlecloudrobotics/core/src/go/pkg/apis/registry/v1alpha1"
	registryv1alpha1 "github.com/googlecloudrobotics/core/src/go/pkg/client/versioned/typed/registry/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeRobots implements RobotInterface
type fakeRobots struct {
	*gentype.FakeClientWithList[*v1alpha1.Robot, *v1alpha1.RobotList]
	Fake *FakeRegistryV1alpha1
}

func newFakeRobots(fake *FakeRegistryV1alpha1, namespace string) registryv1alpha1.RobotInterface {
	return &fakeRobots{
		gentype.NewFakeClientWithList[*v1alpha1.Robot, *v1alpha1.RobotList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("robots"),
			v1alpha1.SchemeGroupVersion.WithKind("Robot"),
			func() *v1alpha1.Robot { return &v1alpha1.Robot{} },
			func() *v1alpha1.RobotList { return &v1alpha1.RobotList{} },
			func(dst, src *v1alpha1.RobotList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.RobotList) []*v1alpha1.Robot { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.RobotList, items []*v1alpha1.Robot) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
