// Copyright 2026 The Cloud Robotics Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/googlecloudrobotics/core/src/go/pkg/apis/apps/v1alpha1"
	appsv1alpha1 "github.com/googlecloudrobotics/core/src/go/pkg/client/versioned/typed/apps/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeResourceSets implements ResourceSetInterface
type fakeResourceSets struct {
	*gentype.FakeClientWithList[*v1alpha1.ResourceSet, *v1alpha1.ResourceSetList]
	Fake *FakeAppsV1alpha1
}

func newFakeResourceSets(fake *FakeAppsV1alpha1) appsv1alpha1.ResourceSetInterface {
	return &fakeResourceSets{
		gentype.NewFakeClientWithList[*v1alpha1.ResourceSet, *v1alpha1.ResourceSetList](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("resourcesets"),
			v1alpha1.SchemeGroupVersion.WithKind("ResourceSet"),
			func() *v1alpha1.ResourceSet { return &v1alpha1.ResourceSet{} },
			func() *v1alpha1.ResourceSetList { return &v1alpha1.ResourceSetList{} },
			func(dst, src *v1alpha1.ResourceSetList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ResourceSetList) []*v1alpha1.ResourceSet {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ResourceSetList, items []*v1alpha1.ResourceSet) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
