# This includes all resources expanded from the prometheus-operator chart using
# the values in ../prometheus-cloud.values.yaml.
# Some pseudo-variables that were inserted there are replaced with actual runtime values.
{{- $data := .Files.Get "files/prometheus-operator-chart.robot.yaml" | replace "${CLOUD_ROBOTICS_DOMAIN}" .Values.domain | replace "${GCP_PROJECT_ID}" .Values.project | replace "HELM-NAMESPACE" .Release.Namespace -}}

# Inject the externalLabels as a pre-formatted YAML block to allow users to define multiple labels in a dict
{{- $prometheusExternalLabelsMap := dict -}}
{{- if .Values.prometheus -}}
  {{- if .Values.prometheus.prometheusSpec -}}
    {{- $prometheusExternalLabelsMap = .Values.prometheus.prometheusSpec.externalLabels -}}
  {{- end -}}
{{- end -}}
{{- if $prometheusExternalLabelsMap }}
  {{- $formattedExternalLabels := toYaml $prometheusExternalLabelsMap | nindent 6 -}}
  {{- $data = $data | replace "${PROMETHEUS_EXTERNAL_LABELS}" $formattedExternalLabels -}}
{{- else }}
  {{- $data = $data | replace "${PROMETHEUS_EXTERNAL_LABELS}" " {}" -}}
{{- end }}

# Inject remoteWrite
{{- $prometheusRemoteWriteList := dict -}}
{{- if .Values.prometheus }}
  {{- if .Values.prometheus.prometheusSpec }}
    {{- if .Values.prometheus.prometheusSpec.remoteWrite }}
      {{- $prometheusRemoteWriteList = .Values.prometheus.prometheusSpec.remoteWrite -}}
    {{- end }}
  {{- end }}
{{- end }}
{{- if $prometheusRemoteWriteList }}
  {{- $formattedRemoteWriteObject := toYaml $prometheusRemoteWriteList | nindent 4 -}}
  {{- $data = $data | replace "- url: ${CR_PROMETHEUS_REMOTE_WRITE_OBJECT}" $formattedRemoteWriteObject -}}
{{- else }}
  {{- $data = $data | replace "  remoteWrite:\n    - url: ${CR_PROMETHEUS_REMOTE_WRITE_OBJECT}" "" -}}
{{- end }}

# Inject containers
{{- $prometheusContainersList := dict -}}
{{- if .Values.prometheus }}
  {{- if .Values.prometheus.prometheusSpec }}
    {{- if .Values.prometheus.prometheusSpec.containers }}
      {{- $prometheusContainersList = .Values.prometheus.prometheusSpec.containers -}}
    {{- end }}
  {{- end }}
{{- end }}
{{- if $prometheusContainersList }}
  {{- $formattedContainersObject := toYaml $prometheusContainersList | nindent 4 -}}
  {{- $data = $data | replace "- name: ${CR_PROMETHEUS_CONTAINERS_OBJECT}" $formattedContainersObject -}}
{{- else }}
  {{- $data = $data | replace "\n    - name: ${CR_PROMETHEUS_CONTAINERS_OBJECT}" "" -}}
{{- end }}

# Inject volumes
{{- $prometheusVolumesList := dict -}}
{{- if .Values.prometheus }}
  {{- if .Values.prometheus.prometheusSpec }}
    {{- if .Values.prometheus.prometheusSpec.volumes }}
      {{- $prometheusVolumesList = .Values.prometheus.prometheusSpec.volumes -}}
    {{- end }}
  {{- end }}
{{- end }}
{{- if $prometheusVolumesList }}
  {{- $formattedVolumesObject := toYaml $prometheusVolumesList | nindent 4 -}}
  {{- $data = $data | replace "- name: ${CR_PROMETHEUS_VOLUMES_OBJECT}" $formattedVolumesObject -}}
{{- else }}
  {{- $data = $data | replace "  volumes:\n    - name: ${CR_PROMETHEUS_VOLUMES_OBJECT}" "" -}}
{{- end }}

# Inject Service Account Annotations
{{- $prometheusSAAnnotationsMap := dict -}}
{{- if .Values.prometheus }}
  {{- if .Values.prometheus.serviceAccount }}
    {{- if .Values.prometheus.serviceAccount.annotations }}
      {{- $prometheusSAAnnotationsMap = .Values.prometheus.serviceAccount.annotations -}}
    {{- end }}
  {{- end }}
{{- end }}
{{- if $prometheusSAAnnotationsMap }}
  {{- $prometheusSAAnnotationsRawYaml := toYaml $prometheusSAAnnotationsMap -}}
  {{- $formattedSAAnnotationsObject := $prometheusSAAnnotationsRawYaml | indent 4 -}}
  {{- $data = $data | replace "    ${CR_PROMETHEUS_SA_ANNOTATIONS}: \"\"" $formattedSAAnnotationsObject -}}
{{- else }}
  {{- $data = $data | replace "  annotations:\n    ${CR_PROMETHEUS_SA_ANNOTATIONS}: \"\"\n" "" -}}
{{- end }}

{{ $data }}
