{{ if and (eq .Values.robot_authentication "true") (ne .Values.project "") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcr-credential-refresher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcr-credential-refresher
  template:
    metadata:
      labels:
        app: gcr-credential-refresher
    spec:
      containers:
      - image: {{ .Values.registry }}{{ .Values.images.gcr_credential_refresher }}
        args:
        - --robot_id_file=/credentials/robot-id.json
        name: gcr-credential-refresher
        resources:
          requests:
            cpu: "1m"
            memory: "50Mi"
          limits:
            cpu: "10m"
            memory: "200Mi"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true  
        volumeMounts:
        - mountPath: /credentials
          name: robot-id
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
      volumes:
      - name: robot-id
        secret:
          secretName: robot-auth
          items:
          - key: json
            path: robot-id.json
{{ end }}
