load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")
load("@rules_oci//oci:defs.bzl", "oci_image")
load("//bazel:crc_image_layer.bzl", "crc_image_layer")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "go_default_library",
    srcs = ["main.go"],
    importpath = "github.com/googlecloudrobotics/core/src/go/cmd/status-echo-server",
    visibility = ["//visibility:private"],
    deps = [
        "@com_github_googlecloudrobotics_ilog//:go_default_library",
    ],
)

go_binary(
    name = "status-echo-server-app",
    embed = [":go_default_library"],
)

crc_image_layer(
    name = "status-echo-server-image-layer",
    srcs = [":status-echo-server-app"],
)

oci_image(
    name = "status-echo-server-image",
    base = "@distroless_base",
    entrypoint = ["/status-echo-server-app"],
    tars = [":status-echo-server-image-layer"],
)

go_test(
    name = "go_default_test",
    srcs = ["main_test.go"],
    embed = [":go_default_library"],
)
