// package http_relay is generated by the proto compiler during the build
// process. This dummy file exists to make the Golang toolchain happy.
// We may need to replace it with a generated file to truly fix the build,
// though.
package http_relay
