apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apps.apps.cloudrobotics.com
  annotations:
    helm.sh/resource-policy: keep
spec:
  group: apps.cloudrobotics.com
  names:
    kind: App
    plural: apps
    singular: app
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                repository:
                  type: string
                version:
                  type: string
                components:
                  type: object
                  properties:
                    cloud:
                      type: object
                      properties:
                        name:
                          type: string
                        inline:
                          type: string
                    robots:
                      type: object
                      properties:
                        name:
                          type: string
                        inline:
                          type: string
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: approllouts.apps.cloudrobotics.com
  annotations:
    helm.sh/resource-policy: keep
spec:
  group: apps.cloudrobotics.com
  names:
    kind: AppRollout
    plural: approllouts
    singular: approllout
  scope: Cluster
  versions: 
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
      - jsonPath: .status.assignments
        name: Assignments
        type: integer
      - jsonPath: .status.readyAssignments
        name: Ready
        type: integer
      - jsonPath: .status.failedAssignments
        name: Failed
        type: integer
      - jsonPath: .metadata.creationTimestamp
        name: Age
        type: date
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                appName:
                  type: string
                cloud:
                  type: object
                  properties:
                    values:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                robots:
                  type: array
                  items:
                    type: object
                    properties:
                      values:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      version:
                        type: string
                      selector:
                        type: object
                        properties:
                          any:
                            type: boolean
                          matchLabels:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                          matchExpressions:
                            type: array
                            items:
                              type: object
                              properties:
                                key:
                                  type: string
                                operator:
                                  type: string
                                values:
                                  type: array
                                  items:
                                    type: string
            status:
              type: object
              properties:
                observedGeneration:
                  type: integer
                assignments:
                  type: integer
                readyAssignments:
                  type: integer
                settledAssignments:
                  type: integer
                failedAssignments:
                  type: integer
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      lastUpdateTime:
                        type: string
                        format: date-time
                      lastTransitionTime:
                        type: string
                        format: date-time
                      status:
                        type: string
                      type:
                        type: string
                      message:
                        type: string
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: chartassignments.apps.cloudrobotics.com
  annotations:
    cr-syncer.cloudrobotics.com/spec-source: cloud
    cr-syncer.cloudrobotics.com/filter-by-robot-name: "True"
    helm.sh/resource-policy: keep
spec:
  group: apps.cloudrobotics.com
  names:
    kind: ChartAssignment
    plural: chartassignments
    singular: chartassignment
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
      - jsonPath: .status.phase
        name: Phase
        type: string
      - jsonPath: .status.observedGeneration
        name: Generation
        type: integer
      - jsonPath: .metadata.creationTimestamp
        name: Age
        type: date
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                clusterName:
                  type: string
                namespaceName:
                  type: string
                chart:
                  type: object
                  properties:
                    repository:
                      type: string
                    name:
                      type: string
                    version:
                      type: string
                    inline:
                      type: string
                    values:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties:
                observedGeneration:
                  type: integer
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      lastUpdateTime:
                        type: string
                        format: date-time
                      lastTransitionTime:
                        type: string
                        format: date-time
                      status:
                        type: string
                      type:
                        type: string
                      message:
                        type: string
                phase:
                  type: string
