apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-ca
spec:
  isCA: true
  duration: 8760h # 1year. This needs to be at least 3x 90days
  commonName: {{ .Values.domain }}
  secretName: cluster-authority
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
{{ if .Values.certificate_provider }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloud-robotics
spec:
  commonName: {{ .Values.domain }}
  secretName: tls
  dnsNames:
    - {{ .Values.domain }}
{{ if eq .Values.certificate_provider "lets-encrypt" }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
{{ else if eq .Values.certificate_provider "google-cas" }}
  issuerRef:
    name: google-cas
    group: cas-issuer.jetstack.io
    kind: GoogleCASClusterIssuer
{{ end }}
{{ end }}
