apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloud-robotics
spec:
  secretName: tls
  issuerRef:
    name: letsencrypt-prod
  commonName: {{ .Values.domain }}
  dnsNames:
    - {{ .Values.domain }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - {{ .Values.domain }}
