{{- if eq .Values.use_istio "true" }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: crc-gateway
  annotations:
    # Use standard K8s annotations for cloud-specific LB settings
    networking.istio.io/service-type: LoadBalancer
    networking.istio.io/service-externalTrafficPolicy: Local
spec:
  gatewayClassName: istio # Provisions Istio-managed LB infrastructure
  addresses:
  - value: {{ .Values.ingress_ip }}
    type: IPAddress
  listeners:
  - name: http
    # hostname: {{ .Values.domain }} # Uncomment to restrict this listener to the configured domain. Required if multiple Gateways share the same IP.
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: All
  - name: https
    # hostname: {{ .Values.domain }} # Uncomment to restrict this listener to the configured domain. Required if multiple Gateways share the same IP (via SNI).
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
      - name: tls
        kind: Secret
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-redirect
spec:
  parentRefs:
  - name: crc-gateway
    sectionName: http
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: crc-auth-gateway
  annotations:
    networking.istio.io/service-type: ClusterIP # only require internal cluster ip
spec:
  gatewayClassName: istio # Provisions Istio-managed LB
  listeners:
    - name: http
      hostname: {{ .Values.domain }}
      protocol: HTTP
      port: 8080
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: crc-gateway-auth
spec:
  targetRefs: # assoc this global auth policy on external crc-gateway
  - kind: Gateway
    group: gateway.networking.k8s.io
    name: crc-gateway
  action: CUSTOM
  provider:
    name: "crc-auth-gateway" # Must match name in meshConfig.extensionProviders exactly.
  rules:
  # targeting all paths.
  # it is also possible to specify the relevant paths here, so that not all requests will be daisy-chained
  - {}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: crc-auth-catchall
spec:
  parentRefs:
  - name: crc-auth-gateway
    namespace: default
    sectionName: http
  hostnames:
  - {{ .Values.domain }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: crc-auth-gateway-catchall-svc
      namespace: default
      port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crc-auth-gateway-catchall-svc
  labels:
    app: crc-auth-gateway-catchall-svc
spec:
  selector:
    matchLabels:
      app: crc-auth-gateway-catchall-svc
  template:
    metadata:
      labels:
        app: crc-auth-gateway-catchall-svc
    spec:
      containers:
      - name: catchall
        image: {{ .Values.registry }}{{ .Values.images.status_echo_server }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        args:
        - --port=8080
        - --http_status=404
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 2 
          periodSeconds: 5
        livenessProbe:
          httpGet: 
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 2 
          periodSeconds: 5
        resources:
          requests:
            cpu: "1.0"
            memory: "32Mi"
          limits:
            cpu: "1.5"
            memory: "64Mi"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          privileged: false
          capabilities:
              drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: crc-auth-gateway-catchall-pdb
spec:
  maxUnavailable: 33%
  selector:
    matchLabels:
      app: crc-auth-gateway-catchall-svc
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: crc-auth-gateway-catchall-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: crc-auth-gateway-catchall-svc
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: crc-auth-gateway-catchall-svc
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: crc-auth-gateway-catchall-svc
{{- end}}
