apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kubernetes-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"  # seconds
    kubernetes.io/ingress.class: "nginx"
    # The web client will reach us through the oauth2-proxy and we need
    # to copy the forwarded access token to an authorization header. Prefer
    # X-Forwarded-Access-Token in case the browser sends a spurious Authorization.
    nginx.ingress.kubernetes.io/configuration-snippet: |
        set_by_lua_block $auth {
          if ngx.var.http_x_forwarded_access_token then
            return "Bearer " .. ngx.var.http_x_forwarded_access_token
          end
          if ngx.var.http_authorization then
            return ngx.var.http_authorization
          end
          return ""
        }
        proxy_set_header Authorization $auth;
spec:
  tls:
  - hosts:
    - {{ .Values.domain }}
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /apis/core.kubernetes($|/)(.*)
        backend:
          serviceName: kubernetes
          servicePort: 443
