{{ if .Values.onprem_federation }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"  # seconds
    nginx.ingress.kubernetes.io/client-body-buffer-size: "50m"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.domain }}
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /apis/core.kubernetes($|/)(.*)
        pathType: Prefix
        backend:
          service:
            name: kubernetes
            port:
              number: 443
{{ end }}