apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: robottypes.registry.cloudrobotics.com
  annotations:
    cr-syncer.cloudrobotics.com/spec-source: cloud
    helm.sh/resource-policy: keep
spec:
  group: registry.cloudrobotics.com
  version: v1alpha1
  names:
    kind: RobotType
    plural: robottypes
    singular: robottype
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          required: ['make', 'model']
          maxProperties: 2
          properties:
            make:
              type: string
            model:
              type: string
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: robots.registry.cloudrobotics.com
  annotations:
    cr-syncer.cloudrobotics.com/filter-by-robot-name: "True"
    cr-syncer.cloudrobotics.com/status-subtree: "robot"
    cr-syncer.cloudrobotics.com/spec-source: cloud
    helm.sh/resource-policy: keep
spec:
  group: registry.cloudrobotics.com
  version: v1alpha1
  names:
    kind: Robot
    plural: robots
    singular: robot
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          maxProperties: 3
          properties:
            type:
              type: string
            project:
              type: string
        status:
          type: object
          properties:
            cloud:
              type: object
            robot:
              type: object
              properties:
                updateTime:
                  type: string
                state:
                  type: string
                  enum:
                    - UNDEFINED
                    - UNAVAILABLE
                    - AVAILABLE
                    - EMERGENCY_STOP
                    - ERROR
                lastStateChangeTime:
                  type: string
                batteryPercentage:
                  type: number
                emergencyStopButtonPressed:
                  type: boolean
            configuration:
              type: object
              properties:
                trolleyAttached:
                  type: boolean
