// Copyright 2026 The Cloud Robotics Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/googlecloudrobotics/core/src/go/pkg/client/informers/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Apps returns a AppInformer.
	Apps() TypedAppInformer
	// AppRollouts returns a AppRolloutInformer.
	AppRollouts() TypedAppRolloutInformer
	// ChartAssignments returns a ChartAssignmentInformer.
	ChartAssignments() TypedChartAssignmentInformer
	// ResourceSets returns a ResourceSetInformer.
	ResourceSets() TypedResourceSetInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Apps returns a TypedAppInformer.
func (v *version) Apps() TypedAppInformer {
	return &appInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// AppRollouts returns a TypedAppRolloutInformer.
func (v *version) AppRollouts() TypedAppRolloutInformer {
	return &appRolloutInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// ChartAssignments returns a TypedChartAssignmentInformer.
func (v *version) ChartAssignments() TypedChartAssignmentInformer {
	return &chartAssignmentInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// ResourceSets returns a TypedResourceSetInformer.
func (v *version) ResourceSets() TypedResourceSetInformer {
	return &resourceSetInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
