// Copyright 2026 The Cloud Robotics Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	registryv1alpha1 "github.com/googlecloudrobotics/core/src/go/pkg/apis/registry/v1alpha1"
	scheme "github.com/googlecloudrobotics/core/src/go/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// RobotsGetter has a method to return a RobotInterface.
// A group's client should implement this interface.
type RobotsGetter interface {
	Robots(namespace string) RobotInterface
}

// RobotInterface has methods to work with Robot resources.
type RobotInterface interface {
	Create(ctx context.Context, robot *registryv1alpha1.Robot, opts v1.CreateOptions) (*registryv1alpha1.Robot, error)
	Update(ctx context.Context, robot *registryv1alpha1.Robot, opts v1.UpdateOptions) (*registryv1alpha1.Robot, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, robot *registryv1alpha1.Robot, opts v1.UpdateOptions) (*registryv1alpha1.Robot, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*registryv1alpha1.Robot, error)
	List(ctx context.Context, opts v1.ListOptions) (*registryv1alpha1.RobotList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *registryv1alpha1.Robot, err error)
	RobotExpansion
}

// robots implements RobotInterface
type robots struct {
	*gentype.ClientWithList[*registryv1alpha1.Robot, *registryv1alpha1.RobotList]
}

// newRobots returns a Robots
func newRobots(c *RegistryV1alpha1Client, namespace string) *robots {
	return &robots{
		gentype.NewClientWithList[*registryv1alpha1.Robot, *registryv1alpha1.RobotList](
			"robots",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *registryv1alpha1.Robot { return &registryv1alpha1.Robot{} },
			func() *registryv1alpha1.RobotList { return &registryv1alpha1.RobotList{} },
		),
	}
}
