// Copyright 2026 The Cloud Robotics Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	appsv1alpha1 "github.com/googlecloudrobotics/core/src/go/pkg/apis/apps/v1alpha1"
	scheme "github.com/googlecloudrobotics/core/src/go/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// AppsGetter has a method to return a AppInterface.
// A group's client should implement this interface.
type AppsGetter interface {
	Apps() AppInterface
}

// AppInterface has methods to work with App resources.
type AppInterface interface {
	Create(ctx context.Context, app *appsv1alpha1.App, opts v1.CreateOptions) (*appsv1alpha1.App, error)
	Update(ctx context.Context, app *appsv1alpha1.App, opts v1.UpdateOptions) (*appsv1alpha1.App, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*appsv1alpha1.App, error)
	List(ctx context.Context, opts v1.ListOptions) (*appsv1alpha1.AppList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *appsv1alpha1.App, err error)
	AppExpansion
}

// apps implements AppInterface
type apps struct {
	*gentype.ClientWithList[*appsv1alpha1.App, *appsv1alpha1.AppList]
}

// newApps returns a Apps
func newApps(c *AppsV1alpha1Client) *apps {
	return &apps{
		gentype.NewClientWithList[*appsv1alpha1.App, *appsv1alpha1.AppList](
			"apps",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *appsv1alpha1.App { return &appsv1alpha1.App{} },
			func() *appsv1alpha1.AppList { return &appsv1alpha1.AppList{} },
		),
	}
}
