// Copyright 2026 The Cloud Robotics Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	appsv1alpha1 "github.com/googlecloudrobotics/core/src/go/pkg/apis/apps/v1alpha1"
	scheme "github.com/googlecloudrobotics/core/src/go/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ResourceSetsGetter has a method to return a ResourceSetInterface.
// A group's client should implement this interface.
type ResourceSetsGetter interface {
	ResourceSets() ResourceSetInterface
}

// ResourceSetInterface has methods to work with ResourceSet resources.
type ResourceSetInterface interface {
	Create(ctx context.Context, resourceSet *appsv1alpha1.ResourceSet, opts v1.CreateOptions) (*appsv1alpha1.ResourceSet, error)
	Update(ctx context.Context, resourceSet *appsv1alpha1.ResourceSet, opts v1.UpdateOptions) (*appsv1alpha1.ResourceSet, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, resourceSet *appsv1alpha1.ResourceSet, opts v1.UpdateOptions) (*appsv1alpha1.ResourceSet, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*appsv1alpha1.ResourceSet, error)
	List(ctx context.Context, opts v1.ListOptions) (*appsv1alpha1.ResourceSetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *appsv1alpha1.ResourceSet, err error)
	ResourceSetExpansion
}

// resourceSets implements ResourceSetInterface
type resourceSets struct {
	*gentype.ClientWithList[*appsv1alpha1.ResourceSet, *appsv1alpha1.ResourceSetList]
}

// newResourceSets returns a ResourceSets
func newResourceSets(c *AppsV1alpha1Client) *resourceSets {
	return &resourceSets{
		gentype.NewClientWithList[*appsv1alpha1.ResourceSet, *appsv1alpha1.ResourceSetList](
			"resourcesets",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *appsv1alpha1.ResourceSet { return &appsv1alpha1.ResourceSet{} },
			func() *appsv1alpha1.ResourceSetList { return &appsv1alpha1.ResourceSetList{} },
		),
	}
}
