{
 "title": "Token Vendor",
 "description": "token-vendor stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Successful Requests",
   "type": "timeseries",
   "description": "successful token requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(tokens_requested{result=\"success\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "timeseries",
   "description": "failed token requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(tokens_requested{result=\"failed\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Verifications",
   "type": "timeseries",
   "description": "successful token verifications",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(tokens_verified{result=\"success\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Verifications",
   "type": "timeseries",
   "description": "failed token verifications",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(tokens_verified{result=\"failed\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}