{{- if .Values.enable_cloud_prometheus }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  hostnames:
  - {{ .Values.domain }}
  parentRefs:
  - name: crc-gateway
    namespace: default
    sectionName: https
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /prometheus/
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: kube-prometheus
      port: 9090
  - matches:
    - path:
        type: Exact
        value: /prometheus
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplaceFullPath
          replaceFullPath: /
    backendRefs:
    - name: kube-prometheus
      port: 9090
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: prometheus-auth
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: prometheus
  action: CUSTOM
  provider:
    name: auth-provider-oauth
{{- end }}
