{{- if .Values.webhook.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: chart-assignment-controller
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: webhook
      protocol: TCP
      name: webhook
  selector:
    app: chart-assignment-controller
{{- end }}
