apiVersion: v1
kind: ServiceAccount
metadata:
  name: chart-assignment-controller
  annotations:
    iam.gke.io/gcp-service-account: "chart-assignment-controller@{{ .Values.project }}.iam.gserviceaccount.com"
