{{- if .Values.webhook.enabled -}}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: chart-assignment-controller
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/chart-assignment-controller
webhooks:
  - name: chartassignments.apps.cloudrobotics.com
    admissionReviewVersions: ["v1"]
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: chart-assignment-controller
        path: /chartassignment/validate
    rules:
      - apiGroups:
          - apps.cloudrobotics.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - chartassignments
    sideEffects: None
{{- end }}
