{{- if .Values.webhook.enabled -}}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "chart-assignment-controller.fullname" . }}
  labels:
    {{- include "chart-assignment-controller.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "chart-assignment-controller.fullname" . }}
webhooks:
  - name: chartassignments.apps.cloudrobotics.com
    admissionReviewVersions: ["v1"]
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "chart-assignment-controller.fullname" . }}
        path: /chartassignment/validate
    rules:
      - apiGroups:
          - apps.cloudrobotics.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - chartassignments
    sideEffects: None
{{- end }}
