apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kubernetes-relay-client
spec:
  hostnames:
  - {{ .Values.domain }}
  parentRefs:
  - name: crc-gateway
    namespace: default
    sectionName: https
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /apis/core.kubernetes-relay/client
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /client
    timeouts:
      backendRequest: 86400s
    backendRefs:
    - name: kubernetes-relay-server
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kubernetes-relay-server
spec:
  hostnames:
  - {{ .Values.domain }}
  parentRefs:
  - name: crc-gateway
    namespace: default
    sectionName: https
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /apis/core.kubernetes-relay/server
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /server
    backendRefs:
    - name: kubernetes-relay-server
      port: 80
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: kubernetes-relay-client-auth
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: kubernetes-relay-client
  action: CUSTOM
  provider:
    name: auth-provider-tv-robots-true
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: kubernetes-relay-server-auth
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: kubernetes-relay-server
  action: CUSTOM
  provider:
    name: auth-provider-tv-robots-false
