apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kubernetes-relay-client
spec:
  hostnames:
  - {{ .Values.domain }}
  parentRefs:
  - name: crc-gateway
    namespace: default
    sectionName: https
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /apis/core.kubernetes-relay/client
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /client
    timeouts:
      request: 86400s
      backendRequest: 86400s
    backendRefs:
    - name: kubernetes-relay-server
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kubernetes-relay-server
spec:
  hostnames:
  - {{ .Values.domain }}
  parentRefs:
  - name: crc-gateway
    namespace: default
    sectionName: https
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /apis/core.kubernetes-relay/server
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /server
    timeouts:
      request: 86400s
      backendRequest: 86400s
    backendRefs:
    - name: kubernetes-relay-server
      port: 80
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: kubernetes-relay-client-auth
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: kubernetes-relay-client
  extAuth:
    contextExtensions:
    - name: robot
      value: "false"
    - name: scopes
      value: "tokenvendor,tvhuman"
    headersToExtAuth:
    - authorization
    - cookie
    - x-forwarded-access-token
    - x-forwarded-host
    - apikey-token
    - x-server-name
    failOpen: false
    grpc:
      backendRefs:
      - name: token-vendor
        namespace: app-token-vendor
        port: 9091
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: kubernetes-relay-server-auth
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: kubernetes-relay-server
  extAuth:
    contextExtensions:
    - name: robot
      value: "true"
    - name: scopes
      value: "tokenvendor,tvrobot"
    headersToExtAuth:
    - authorization
    - cookie
    - x-forwarded-access-token
    - x-forwarded-host
    - apikey-token
    - x-server-name
    failOpen: false
    grpc:
      backendRefs:
      - name: token-vendor
        namespace: app-token-vendor
        port: 9091



