apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes-relay-client
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://token-vendor.default.svc.cluster.local/apis/core.token-vendor/v1/token.verify"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "50m"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    # proxy-read-timeout sets how long nginx will allow a request to be idle
    # for. This is important for requests like `kubectl logs -f` where the logs
    # may be silent for some time.
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
    nginx.ingress.kubernetes.io/rewrite-target: /client/$2
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /apis/core.kubernetes-relay/client($|/)(.*)
        pathType: Prefix
        backend:
          service:
            name: kubernetes-relay-server
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes-relay-server
  annotations:
    nginx.ingress.kubernetes.io/client-body-buffer-size: "50m"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/rewrite-target: /server/$2
    nginx.ingress.kubernetes.io/auth-url: "http://token-vendor.default.svc.cluster.local/apis/core.token-vendor/v1/token.verify?robots=true"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /apis/core.kubernetes-relay/server($|/)(.*)
        pathType: Prefix
        backend:
          service:
            name: kubernetes-relay-server
            port:
              number: 80
