apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-relay-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-relay-server
  template:
    metadata:
      labels:
        app: kubernetes-relay-server
    spec:
      containers:
      - name: kubernetes-relay-server
        image: {{ .Values.registry }}{{ .Values.images.http_relay_server }}
        args:
        - --port=8080
        env:
        # Enable tracebacks for debugging deadlocks or hanging requests.
        - name: GOTRACEBACK
          value: all
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 10
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            memory: "16Mi"
            cpu: "100m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532

