apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-relay-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-relay-server
  template:
    metadata:
      labels:
        app: kubernetes-relay-server
    spec:
      containers:
      - name: server
        image: {{ .Values.registry }}{{ .Values.images.http_relay_server }}
        args:
        - --port=8080
        - --project_id={{ .Values.project }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
        ports:
        - name: http
          containerPort: 8080
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532

