# MetricRelabelConfigs to apply to samples after scraping, but before ingestion.
prometheus:
  serviceMonitor:
    metricRelabelings:  []

kubernetes_relay_server:
  resources:
    requests:
      memory: "16Mi"
      cpu: "100m"
