image:
  repository: '{{ .Values.registry }}{{ splitList `@` .Values.images.chart_assignment_controller | first }}'
  digest: '{{ splitList `@` .Values.images.chart_assignment_controller | last }}'
cloudCluster: false
robotName: '{{ .Values.robot.name }}'
webhook:
  enabled: true
rbac:
  create: true
  clusterAdmin: true
