image:
  pullPolicy: IfNotPresent

env:
  - name: MY_NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName

## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/configuration-file
config:
  service: |
    [SERVICE]
        Daemon Off
        Flush {{ .Values.flush }}
        Log_Level {{ .Values.logLevel }}
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port {{ .Values.metricsPort }}
        Health_Check On

  ## https://docs.fluentbit.io/manual/pipeline/parsers
  customParsers: |
    # Merges multi-line Abseil logs. The regexs assume that any line which does not start
    # with an Abseil log preamble is part of the previous log message. No assumptions on
    # indentation or similar are made.
    [MULTILINE_PARSER]
        Name          absl_logs_multiline
        Type          regex
        Flush_timeout 1000
        #
        # Regex rules for multiline parsing
        # ---------------------------------
        #
        # configuration hints:
        #
        #  - first state always has the name: start_state
        #  - every field in the rule must be inside double quotes
        #
        # rules |   state name  | regex pattern                                                         | next state
        # ------|---------------|---------------------------------------------------------------------------------------------
        Rule      "start_state"   "/^((W|I|E|F))([0-9]{4}) ([^ ]+)\s+([-0-9]+) (\S+:\d+)] (.*)$/"           "cont"
        Rule      "cont"          "/^(?!(((W|I|E|F))([0-9]{4}) ([^ ]+)\s+([-0-9]+) (\S+:\d+)]))(.*)$/"      "cont"

    # A parser for Abseil log files: https://abseil.io/docs/cpp/guides/logging#prefix
    [PARSER]
        Name        absl_logs
        Format      regex
        Regex       ^(?<severity>(W|I|E|F))([0-9]{4}) (?<time>[^ ]+)\s+(?<pid>[-0-9]+) (?<source>\S+:\d+)] (?<message>[\s\S]*)$
        Time_Key    time
        Time_Format %H:%M:%S.%L
        Time_Keep   On
        Types       pid:integer

  ## https://docs.fluentbit.io/manual/pipeline/inputs
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        # Adding the 'absl_logs_multiline' does not work as intended.
        # It must be specified as a dedicated filter (see below).
        Multiline.Parser docker, cri, go, python
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag k8s_node.${MY_NODE_NAME}
        Systemd_Filter  _SYSTEMD_UNIT=containerd.service
        Systemd_Filter  _SYSTEMD_UNIT=etcd.service
        Systemd_Filter  _SYSTEMD_UNIT=kube-apiserver.service
        Systemd_Filter  _SYSTEMD_UNIT=kube-controller-manager.service
        Systemd_Filter  _SYSTEMD_UNIT=kube-scheduler.service
        Systemd_Filter  _SYSTEMD_UNIT=kubelet.service
        Systemd_Filter  _SYSTEMD_UNIT=sshd.service
        Read_From_Tail On

    [INPUT]
        Name            node_exporter_metrics
        Tag             node_metrics
        Scrape_interval 10

  ## https://docs.fluentbit.io/manual/pipeline/filters
  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    # Joins multiple Abseil logs into a single line.
    [FILTER]
        Name                    multiline
        Match                   kube.*
        Multiline.Key_content   log
        Multiline.Parser        absl_logs_multiline

    # Applies the absl_logs parser to the 'log' field.
    [FILTER]
        Name          parser
        Match         kube.*
        Key_Name      log
        Parser        absl_logs

    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_equals level info
        Add severity INFO

    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_equals level warning
        Add severity WARNING

    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_equals level warn
        Add severity WARNING

    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_equals level error
        Add severity ERROR

    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_matches log ^.*\[\sinfo\].*$
        Add severity INFO

    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_matches log ^.*\[\swarn\].*$
        Add severity WARNING

    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_matches log .*\[error\].*
        Add severity ERROR

    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_matches log .*(type="Info"|level=info).*
        Add severity INFO

    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_matches log .*(type="Warning"|level=warning).*
        Add severity WARNING

    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_matches log .*(type="Error"|level=error).*
        Add severity ERROR

    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_equals stream stderr
        Add severity ERROR

    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_equals stream stdout
        Add severity INFO

    [FILTER]
        Name          modify
        Match         kube.*
        Remove _p

    [FILTER]
        Name          modify
        Match         kube.*
        Rename log message

  ## https://docs.fluentbit.io/manual/pipeline/outputs
  outputs: |
    [OUTPUT]
        Name stackdriver
        Match kube.*
        Tag_Prefix kube.var.log.containers.
        Resource k8s_container
        k8s_cluster_name MY_ROBOT
        k8s_cluster_location MY_CLUSTER_LOCATION
        severity_key severity
        Workers 1

    [OUTPUT]
        Name stackdriver
        Match k8s_node.*
        Resource k8s_node
        custom_k8s_regex ^(?<node_name>.*)$
        k8s_cluster_name MY_ROBOT
        k8s_cluster_location MY_CLUSTER_LOCATION
        Workers 1

    [OUTPUT]
        name            prometheus_exporter
        match           node_metrics
        port            24231

volumeMounts:
  - name: config
    mountPath: /fluent-bit/etc/fluent-bit.conf
    subPath: fluent-bit.conf
  - name: config
    mountPath: /fluent-bit/etc/custom_parsers.conf
    subPath: custom_parsers.conf

daemonSetVolumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: runlog
    hostPath:
      path: /run/log
  - name: etcmachineid
    hostPath:
      path: /etc/machine-id
      type: File

daemonSetVolumeMounts:
  - name: varlog
    mountPath: /var/log
  - name: runlog
    mountPath: /run/log
  - name: etcmachineid
    mountPath: /etc/machine-id
    readOnly: true

tolerations:
  - key: "rtpc"
    operator: "Exists"
    effect: "NoSchedule"
