{
 "title": "Http Relay",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Broker Requests by method",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (method) (rate(broker_requests[10m]))",
     "legendFormat": "method=\"{{method}}\""
    }
   ]
  },
  {
   "title": "# of successful Broker Responses by method",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (method) (rate(broker_responses{result=\"ok\"}[10m]))",
     "legendFormat": "method=\"{{method}}\""
    }
   ]
  },
  {
   "title": "# of bad Broker Responses by method",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (method,result) (rate(broker_responses{result!~\"(ok|timeout)\"}[10m]))",
     "legendFormat": "method=\"{{method}}\",result=\"{{result}}\""
    }
   ]
  },
  {
   "title": "Broker Requests by relay ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(broker_requests[10m])) ",
     "legendFormat": "job=\"{{job}}\""
    }
   ]
  },
  {
   "title": "# of successful Broker Responses by relay",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(broker_responses{result=\"ok\"}[10m]))",
     "legendFormat": "job=\"{{job}}\""
    }
   ]
  },
  {
   "title": "# of bad Broker Responses by relay",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job,result) (rate(broker_responses{result!~\"(ok|timeout)\"}[10m]))",
     "legendFormat": "job=\"{{job}}\",result=\"{{result}}\""
    }
   ]
  },
  {
   "title": "Broker Requests by client",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (backend) (rate(broker_requests[10m]))",
     "legendFormat": "backend=\"{{backend}}\""
    }
   ]
  },
  {
   "title": "# of successful Broker Responses by client",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (backend) (rate(broker_responses{result=\"ok\"}[10m]))",
     "legendFormat": "backend=\"{{backend}}\""
    }
   ]
  },
  {
   "title": "# of bad Broker Responses by client",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (backend,result) (rate(broker_responses{result!~\"(ok|timeout)\"}[10m]))",
     "legendFormat": "backend=\"{{backend}}\",result=\"{{result}}\""
    }
   ]
  },
  {
   "title": "Request duration (in seconds) histogram",
   "type": "heatmap",
   "description": "Request duration buckets (in seconds) over time.",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(broker_responses_durations_bucket[$__interval])) by (le)"
    }
   ]
  },
  {
   "title": "Number of backends",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "count(count by (backend) (broker_requests))",
     "legendFormat": "number of backends"
    }
   ]
  }
 ]
}