domain: "example.com"
ingress_ip: ""
project: "my-gcp-project"
region: "us-north1-a"
deploy_environment: "GCP"
registry: "gcr.io/my-gcp-project"
owner_email: "info@example.com"

# Setting app_management to "false" will remove layer 2 (app-rollout/chart-assignment-controller, etc).
app_management: "true"

oauth2_proxy:
  cookie_secret: ""
  client_id: ""
  client_secret: ""

# Certificate provider
# This configures different cert-manager templates to emit certificates using the chosen authority.
certificate_provider: ""

# Certificate authority used to sign in-cluster certificates.
certificate_authority:
  key: ""
  crt: ""
