// package helloworld is generated by the proto compiler during the build
// process. This dummy file exists to make `go mod tidy` happy, otherwise it
// can complain:
//
// module github.com/googlecloudrobotics/core@latest found (...), but does not
// contain package github.com/googlecloudrobotics/core/src/proto/hello-world
package helloworld
