load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "go_default_library",
    srcs = ["tracing.go"],
    importpath = "github.com/googlecloudrobotics/core/src/go/pkg/telemetry",
    deps = [
        "@com_github_googlecloudplatform_opentelemetry_operations_go_exporter_trace//:go_default_library",
        "@io_opentelemetry_go_contrib_propagators_b3//:go_default_library",
        "@io_opentelemetry_go_contrib_propagators_opencensus//:go_default_library",
        "@io_opentelemetry_go_otel//:go_default_library",
        "@io_opentelemetry_go_otel//attribute:go_default_library",
        "@io_opentelemetry_go_otel//propagation:go_default_library",
        "@io_opentelemetry_go_otel//semconv/v1.41.0:go_default_library",
        "@io_opentelemetry_go_otel_sdk//resource:go_default_library",
        "@io_opentelemetry_go_otel_sdk//trace:go_default_library",
    ],
)

go_test(
    name = "go_default_test",
    srcs = ["tracing_test.go"],
    embed = [":go_default_library"],
    deps = [
        "@io_opentelemetry_go_otel//propagation:go_default_library",
        "@io_opentelemetry_go_otel_trace//:go_default_library",
    ],
)
